### ISSUE TITLE
Small example idea - Where to put

### ISSUE THREAD

**Issue by bartmate** [quantumlib/unitary#12]
Hi.

I have a small game idea with which move, phased move, superposition (maybe, interference) could be tested: A kind of gamified quantum version of the riddle "Fox and the holes". 
If I implement it, should it be part of the library? Maybe under an examples directory?

Regards,
  Máté

**Comment by cognigami** [comment]
This is great Máté! Do you want to put this in a //unitary/unitary/examples/ directory as part of your PR?
