### ISSUE TITLE
Quantum RPG: Error on death after entering the hole

### ISSUE THREAD

**Issue by cantwellc** [quantumlib/unitary#136]
>enter hole
You feel your entire existence dissolve into errors
as you are pulled apart into static and random bitstrings.
Traceback (most recent call last):
  File "./unitary/examples/quantum_rpg/main_loop.py", line 140, in loop
    msg = action(self.game_state, self.world)
  File "/home/cantwellc/projects/unitary/env/lib/python3.7/site-packages/unitary/examples/quantum_rpg/final_state_preparation/classical_frontier.py", line 106, in _hole
    "You feel your entire existence dissolve into errors\n"
unitary.examples.quantum_rpg.exceptions.UntimelyDeathException: You feel your entire existence dissolve into errors
as you are pulled apart into static and random bitstrings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./unitary/examples/quantum_rpg/main_loop.py", line 236, in <module>
    main(game_state.GameState(party=[]))
  File "./unitary/examples/quantum_rpg/main_loop.py", line 232, in main
    main_loop.loop()
  File "./unitary/examples/quantum_rpg/main_loop.py", line 179, in loop
    print(ascii_art.RIP_TOP, file=self.file)
AttributeError: module 'unitary.examples.quantum_rpg.ascii_art' has no attribute 'RIP_TOP'

**Comment by dstrain115** [comment]
Hmm... is your installation okay?  I cannot reproduce it.  This variable exists:
https://github.com/quantumlib/unitary/blob/main/unitary/examples/quantum_rpg/ascii_art.py#L88

Can you pull main and see if this still exists?

**Comment by cantwellc** [comment]
I just saw the same error when slimes killed me. I see RIP_TOP in ascii_art.py

**Comment by dstrain115** [comment]
I suspect that it could be an issue with your environment.  How are you running it?  Is it possible you have an older branch or some sort of conflicting python path?

I can't reproduce it with a virtualenv on main or with the colab.

**Comment by cantwellc** [comment]
I forked the unitary repo to my personal. My fork is up to date, and my local is up to date with my github fork.
Running in Windows subsystem linux, in a virtualenv with python 3.7.5
It is very possible it could be a conflicting python path. I don't use python very often, maybe I set it up wrong

**Comment by cantwellc** [comment]
I don't recall seeing these errors when I died yesterday

**Comment by cantwellc** [comment]
Also, I'm trying to load this save and it isn't working.              ValueError: invalid literal for int() with base 10: ''

classical12;2;Q#Analyst#3#X0.250000,1#Z0.125000,2#Z0.250000,1#X0.375000,2#H1.000000,1#Z0.125000,2;Zed#Engineer#2#Z0.125000,1#X0.250000,2#X0.250000,

So I have to start over. Do you have a different save string I can try to quickly test?

**Comment by dstrain115** [comment]
It looks like the cut and paste missed the last character.  Try this:

`classical12;2;Q#Analyst#3#X0.250000,1#Z0.125000,2#Z0.250000,1#X0.375000,2#H1.000000,1#Z0.125000,2;Zed#Engineer#2#Z0.125000,1#X0.250000,2#X0.250000,2`

**Comment by cantwellc** [comment]
That works, thanks. My game has no problem with the other things in ascii_art.py, so it seems odd to me that RIP_TOP is a problem

**Comment by cantwellc** [comment]
I tried a fresh install and it works now.

**Comment by dstrain115** [comment]
Great!  Thanks for all the detailed testing and issue filing!  It is very helpful in making the game more robust!
