### ISSUE TITLE
Outdated version of ReCirq code

### ISSUE THREAD

**Issue by losos0** [quantumlib/unitary#17]
The initial copy is missing, at least, https://github.com/quantumlib/ReCirq/pull/278.

**Comment by dstrain115** [comment]
It looks like that PR was copied over, but it was inadvertently squashed by this commit:
https://github.com/quantumlib/unitary/commit/bbfcfc1159e9dedfdb047f191683c5714f22fda2

**Comment by dstrain115** [comment]
I looked at the last 5 or 6 commits in quantum_chess in ReCirq, and I think this is the only commit missing.

@losos0 What do you mean by a history rewrite?  I think the commit history has the history from ReCirq.

**Comment by losos0** [comment]
Oh yes it's there, my bad.
