### ISSUE TITLE
Quantum RPG: Bridge Repair not in the save file

### ISSUE THREAD

**Issue by dstrain115** [quantumlib/unitary#178]
When you repair the bridge, it is not in the save file.  Though, most of the time, you probably cross the bridge, so it's not a huge deal, but it does break continuity a bit.

**Comment by dmasspla** [comment]
Please see [PR#186](https://github.com/quantumlib/unitary/pull/186) as an alternative to fix this issue.

The change is based on including the bridge repair in the save file, and changing the location description to guide the user towards examining the bridge to know if it's broken. Examining the bridge triggers updating the location based on the--reloaded--bridge state.

**Comment by dstrain115** [comment]
Fixed by https://github.com/quantumlib/unitary/pull/186
